"""add due_date to assignment and comment to grade

Revision ID: 1ab6abdebcc6
Revises: b8fc828c5c94
Create Date: 2026-03-12 17:27:44.890781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab6abdebcc6'
down_revision = 'b8fc828c5c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_column('comment')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
